cardapio_online/cardapio_online/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from cardapio.views.index import index
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^cardapio/', include('cardapio.urls')),
    url(r'^categoria/', include('categoria.urls')),
    url(r'^ingrediente/', include('ingrediente.urls')),
    url(r'^item/', include('item.urls')),
    url(r'^acesso/', include('acesso.urls')),
    url(r'^', include ('cardapio.urls')),
    
    

    url(r'^admin/', include(admin.site.urls)), #Criacao de usuarios e grupos
)

cardapio_online/item/urls.py
from django.conf.urls import patterns, url
from item.views.lista_item import lista_item
from item.views.lista_item_serializer import Lista_item_serializer,\
    Criar_item_serializer
from item.views.editar_item import editar_item
from item.views.item_serializer import ItemSerial
from item.views.remover_item import remover_item




urlpatterns = patterns('',
                       
     url(r'^itens/$', lista_item, name='lista_item'),
     url(r'^listar_itens_serial/$',  Lista_item_serializer.as_view(), name='Lista_item_serializer'),
     url(r'^criar_itens_serial/$',  Criar_item_serializer.as_view(), name='Criar_item_serializer'),
     url(r'^item_serial/(?P<pk>[0-9]+)/$',  ItemSerial.as_view(), name='ItemSerial'),
     
     url(r'^add_item/$',          editar_item,          name='adicionar_item'),
     url(r'^editar_item/(?P<id_item>\d+)$', editar_item, name='editar_item'),
     url(r'^remover_item/(?P<id_item>\d+)$', remover_item, name='remover_item')

)

cardapio_online/item/models/item.py
# -*- coding: utf-8 -*-
from django.db import models
from ingrediente.models.ingrediente import Ingrediente
from categoria.models.categoria import Categoria

CATEGORIA_CHOICE = (('', '----------'),
                ('ENTRADAS',('ENTRADAS')),
                ('PRINCIPAL',('PRINCIPAL')),
                ('SOBREMESA',('SOBREMESA')),
                ('BEBIDAS',('BEBIDAS')),               
                )

class Item(models.Model):
    nome    = models.CharField('Nome do item', max_length=100, null = False)
    valor = models.DecimalField('Valor', decimal_places=2, max_digits=9)
    tempo_preparo = models.TimeField("Tempo de preparo")
    ingrediente = models.ManyToManyField(Ingrediente)
    #categoria   = models.CharField('Categoria', max_length=100, choices=CATEGORIA_CHOICE)
    categoria = models.ForeignKey(Categoria)
    
    def __unicode__(self):
        return self.nome
    
    class Meta:
        app_label = 'item'
        
    def ingredientes(self):
        return self.ingrediente.all()

cardapio_online/item/models/item_serializer.py
from item import Item
from rest_framework import serializers


class ItemSerializerList(serializers.ModelSerializer):
    ingrediente = serializers.StringRelatedField(many=True)
    categoria = serializers.StringRelatedField()
    
    class Meta:
        model = Item
        fields = ('id', 'nome', 'valor', 'tempo_preparo', 'ingrediente', 'categoria')
        
class ItemSerializer(serializers.ModelSerializer):
    
    
    class Meta:
        model = Item
        fields = ('id', 'nome', 'valor', 'tempo_preparo', 'ingrediente', 'categoria')

cardapio_online/item/forms/item_form.py
# -*- coding: utf-8 -*-
from django import forms
from item.models.item import Item


class ItemForm(forms.ModelForm):
    
    def __init__(self, *args, **kwargs):         
        super(ItemForm, self).__init__(*args, **kwargs)
        self.fields['nome'].widget.attrs['class'] = "form-control"
        self.fields['valor'].widget.attrs['class'] = "form-control"
        self.fields['tempo_preparo'].widget.attrs['class'] = "form-control"
        self.fields['ingrediente'].widget.attrs['class'] = "form-control"
        self.fields['categoria'].widget.attrs['class'] = "form-control"
        
        
        
    class Meta():
        model = Item
        fields = '__all__' 
    
    

cardapio_online/item/views/editar_item.py
# -*- coding: utf-8 -*-

from django.contrib import messages
from django.shortcuts import render_to_response, redirect
from django.template.context import RequestContext
from item.forms.item_form import ItemForm
from item.models.item import Item




def editar_item(request, id_item=None):
    if id_item:
        instance = Item.objects.get(pk=id_item)
        
    else:
        instance = None
        
    if request.method == 'POST':
        form = ItemForm(request.POST, instance=instance)
        
        if form.is_valid():
            form.save()
            messages.success(request, "Adicionado com sucesso")
            return redirect('listar_item_acesso')
    
    else:
        
        form = ItemForm(instance=instance)
        
        
    
    return render_to_response('editar_item.html', locals(),context_instance=RequestContext(request))
        
        
        
    
        
        
    

cardapio_online/item/views/item_serializer.py
from item.models.item import Item
from rest_framework import generics
from item.models.item_serializer import ItemSerializer, ItemSerializerList

class ItemSerial(generics.RetrieveUpdateDestroyAPIView):
    queryset = Item.objects.all()
    serializer_class = ItemSerializerList

cardapio_online/item/views/lista_item.py
# -*- coding: utf-8 -*-
from django.shortcuts import render_to_response
from django.template import RequestContext
from item.models.item import Item
from categoria.models.categoria import Categoria


def lista_item(request):
    itens = Item.objects.all()
    categorias = Categoria.objects.all()
    
    try:
        buscar_item = request.GET.get('buscar_item').strip().upper()
        buscar_categoria = request.GET.get('buscar_categoria')
        
    except:
        buscar_item = ''
        buscar_categoria = ''
            
    if buscar_item:
        itens = Item.objects.filter(nome__icontains = buscar_item)
        
    if buscar_categoria:
        itens = Item.objects.filter(categoria__id = buscar_categoria)
    

    return render_to_response('lista_item.html',locals(),context_instance=RequestContext(request))


def listar_item_acesso(request):
    itens = Item.objects.all()
    
    try:
        buscar_item = request.GET.get('buscar_item').strip().upper()
        
    except:
        buscar_item = ''
        
    print buscar_item
        
    if buscar_item:
        itens = Item.objects.filter(nome__icontains = buscar_item)
        print itens
        

    
    return render_to_response('listar_item_acesso.html',locals(),context_instance=RequestContext(request))
    

cardapio_online/item/views/lista_item_serializer.py
from item.models.item_serializer import ItemSerializer, ItemSerializerList
from item.models.item import Item
from rest_framework import generics



class Lista_item_serializer(generics.ListAPIView):
    queryset = Item.objects.all()
    serializer_class = ItemSerializerList
    
    
class Criar_item_serializer(generics.CreateAPIView):
    serializer_class = ItemSerializer
    
        

cardapio_online/item/views/remover_item.py
'''
Created on 17/01/2016

@author: Arthur
'''
from django.shortcuts import redirect
from item.models.item import Item

def remover_item(request, id_item):
    item = Item.objects.get(pk=id_item)
    item.delete()

    
    return redirect('listar_item_acesso')

cardapio_online/item/templates/editar_item.html
{% extends 'base_acesso.html' %}
{% load staticfiles %}
{% block css %}
<link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'css/bootstrap-responsive.css' %}" rel="stylesheet">
<link href="{% static 'css/bootstrap-responsive.min.css' %}" rel="stylesheet">

		
 {% endblock css %}
 
{% block content %}  
  
 <div class="container">
    <div class="panel panel-padrao">
    	<div class="col-md-9 col-md-offset-3">
        <div class="panel-heading clearfix">
            
            <h3 class="panel-title text-center">{% if instance %}Alterar Item{% else %}Adicionar Item{% endif %}</h3>
        </div>
        
   	<form class="form-horizontal" role="form" method="post">
   	{% csrf_token %}
  		<div class="form-group {% if form.nome.errors %}has-error{% endif %}" >
   		<label class="control-label col-sm-2">Nome:</label>
		<div class="col-sm-4">{{form.nome}}</div>
        {% if form.nome.errors %}
		<label class="control-label has-error" for="id_nome">{{ form.nome.errors.as_text }}</label>
		{% endif %}
		</div>
		
		<div class="form-group {% if form.valor.errors %}has-error{% endif %}">
   		<label class="control-label col-sm-2">Valor:</label>
		<div class="col-sm-4">{{form.valor}}</div>
        {% if form.valor.errors %}
		<label class="control-label has-error" for="id_valor">{{ form.valor.errors.as_text }}</label>
		{% endif %}
		</div>
		
		
		<div class="form-group {% if form.tempo_preparo.errors %}has-error{% endif %}">
   		<label class="control-label col-sm-2">Tempo de preparo:</label>
		<div class="col-sm-4">{{form.tempo_preparo}}</div>
        {% if form.tempo_preparo.errors %}
		<label class="control-label has-error" for="id_tempo_preparo">{{ form.valor.tempo_preparo.as_text }}</label>
		{% endif %}
		</div>
		
		<div class="form-group {% if form.ingrediente.errors %}has-error{% endif %}">
   		<label class="control-label col-sm-2">Ingrediente:</label>
		<div class="col-sm-4">{{form.ingrediente}}</div>
        {% if form.ingrediente.errors %}
		<label class="control-label has-error" for="id_ingrediente">{{ form.ingrediente.errors.as_text }}</label>
		{% endif %}
		</div>
		
		<div class="form-group {% if form.categoria.errors %}has-error{% endif %}">
   		<label class="control-label col-sm-2">Categoria:</label>
		<div class="col-sm-4">{{form.categoria}}</div>
        {% if form.categoria.errors %}
		<label class="control-label has-error" for="id_categoria">{{ form.categoria.errors.as_text }}</label>
		{% endif %}
		</div>
 	
  		<div class="form-group text-right">
	    	<div class="col-sm-offset-2 col-sm-10">
	      	<button type="submit" class="btn btn-default">{% if instance %} Editar {% else %}Cadastrar{% endif %}</button>
	    	</div>
  		</div>
  
 	</form>
 	</div>
 	
  	</div>
  
 </div>


<script src="{% static 'js/jquery.min.js' %}"></script>
        
{% endblock content %}

cardapio_online/item/templates/lista_item.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block css %}
<link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'css/bootstrap-table.css' %}" rel="stylesheet">
<link href="{% static 'css/bootstrap-responsive.css' %}" rel="stylesheet">
<link href="{% static 'css/bootstrap-responsive.min.css' %}" rel="stylesheet">

		
 {% endblock css %}
 
{% block content %}
<div class="container">
    <div class="panel panel-padrao">
        <div class="panel-heading clearfix">

             <center><img src="{% static 'img/menuicon.png' %}" style="width: 30%; height: 30%;"/></center>
        </div>
        <div class="panel-body">
            <form action="" method="GET">
                <div class="row" style="margin-bottom: 2%;">
                    <div class="col-sm-4">
                        <div class="input-group margin-bottom-sm">
                            <span class="input-group-addon"><i class="fa fa-search fa-fw"></i></span>
                            <input type="search" class="form-control input-sm" name="buscar_item" value="{{ buscar_item }}" placeholder="Buscar um item"/>
			                 
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <select name="buscar_categoria" id="id_categoria" style="width:180px">
								 <option value="" disabled selected style='display:none;'>Selecione a Categoria</option>
								{% if categorias %}
								{%for categoria in categorias%}
									<option value="{{categoria.id}}" {%ifequal categoria.id buscar_categoria %} selected="selected" {%endifequal%}>{{categoria.nome}} </option>
								{%endfor%}
								{% else %}
								 <option value="" disabled selected style='display:none;'>Nenhuma categoria cadastrada</option>
								{% endif %}
						</select>
                    </div>
                    <div class="col-sm-1">
                        <button type="submit" class="btn btn-primary btn-sm">
                            Buscar
                        </button>
                    </div>
                </div>
            </form>
             <table id="table" class="table table-striped table-bordered table-hover"
               data-toggle="table"
               >
            <thead>
            <tr>
                <th data-field="nome" data-sortable="true">Item</th>
                <th data-field="valor" data-sortable="true">Valor</th>
                <th data-field="tempo_preparo" data-sortable="true">Tempo de preparo</th>
                <th data-field="ingrediente" data-sortable="false">Ingredientes</th>
                <th data-field="categoria" data-sortable="false">Categoria</th>
            </tr>
            </thead>
             <tbody>
                        {% if itens %}
	                    
	                        {% for item in itens %}
	                        <tr class="{% cycle 'odd gradeX' 'even gradeC' as rowcolors %}">
	                    
		                            <td align="left">
		                                <span><b>{{item.nome}}</b></span>
		                            </td>
	                            <td>{{item.valor}}</td>
	                            <td>{{item.tempo_preparo}}</td>
	                            <td>
	                            {% for ingrediente in item.ingredientes %}
	                            {{ingrediente.nome}}</br>
	                            {% endfor %}
	                            </td>
	                            
	                           <td>{{item.categoria.nome}}</td>
	                        </tr>
	                        {% endfor %}
                        {% else %}
	                        <tr>
	                            <td colspan="5">
	                              <center>  Nenhum item cadastrado até o momento.</center>
	                            </td>
	                        </tr>
                        {% endif %}
                    </tbody>
        </table>
           
        </div>
    </div>
</div>

<script src="{% static 'js/jquery.min.js' %}"></script>





{% endblock content %}

cardapio_online/item/templates/listar_item_acesso.html
{% extends 'base_acesso.html' %}
{% load staticfiles %}
{% block css %}
<link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'css/bootstrap-table.css' %}" rel="stylesheet">
<link href="{% static 'css/bootstrap-responsive.css' %}" rel="stylesheet">
<link href="{% static 'css/bootstrap-responsive.min.css' %}" rel="stylesheet">
<script src="{% static 'js/bootstrap-table.js' %}"></script>
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/bootstrap.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
 {% endblock css %}
 
{% block content %}
<div class="container">
    <div class="panel panel-padrao">
        <div class="panel-heading clearfix">
			 <div class="col-sm-0 " class="pull-right">
                        <a href="{% url 'adicionar_item' %}" class="btn btn-primary btn-sm  pull-right">Adicionar Item</a>
                        <a href="{% url 'Lista_item_serializer' %}" class="btn btn-primary btn-sm  pull-left">Listar API REST</a>   
                       <div class="col-sm-1"> <a href="{% url 'Criar_item_serializer' %}" class="btn btn-primary btn-sm  pull-left">Criar API REST</a></div>
                        
                    </div>
             <h1 class="text-center">Lista de Itens</h1>
             
             
        </div>
        <div class="panel-body">
            <form action="" method="GET">
                <div class="row" style="margin-bottom: 2%;">
                    <div class="col-sm-4">
                        <div class="input-group margin-bottom-sm">
                            <span class="input-group-addon"><i class="fa fa-search fa-fw"></i></span>
                            <input type="search" class="form-control input-sm" name="buscar_item" value="{{ listar_item_acesso }}" placeholder="Buscar um item"/>
			                 
                        </div>
                    </div>
                   
                    <div class="col-sm-1">
                        <button type="submit" class="btn btn-info btn-sm">
                            Buscar
                        </button>
                    </div>
                </div>
            </form>
             <table id="table" class="table table-striped table-bordered table-hover"
               data-toggle="table"
               >
            <thead>
            <tr>
                <th data-field="nome" data-sortable="false">Id</th>
                <th data-field="valor" data-sortable="true">Nome</th>
                <th data-field="acao" data-sortable="false">Ação</th>
                
               
            </tr>
            </thead>
             <tbody>
                        {% if itens %}
	                    
	                        {% for item in itens %}
	                        <tr class="{% cycle 'odd gradeX' 'even gradeC' as rowcolors %}">
	                    
		                            <td align="left">
		                                 <a class="link" href="{% url 'editar_item' item.id %}"><span><b>{{item.id}}</b></span></a>
		                            </td>
	                            <td align='center'>{{item.nome}}</td>
	                            <td align='right'><a href="{% url 'ItemSerial' item.id %}" class="btn btn-default btn-sm  pull-left">API REST</a>&nbsp;&nbsp;
	                            
								<a href="{% url 'remover_item' item.id %}" class="btn btn-danger  pull-center" onclick="return confirm('Você tem certeza?')">DELETAR</a>	                            
	                            </td>
	                           
	                            
	                           
	                        </tr>
	                        {% endfor %}
                        {% else %}
	                        <tr>
	                            <td colspan="5">
	                              <center>  Nenhum item cadastrado até o momento.</center>
	                            </td>
	                        </tr>
	                        
                        {% endif %}
                    </tbody>
        </table>
           
        </div>
    </div>
</div>



<script src="{% static 'js/bootstrap-table.js' %}"></script>



{% endblock content %}